# Commands to start on workspace startup
tasks:
  - name: Server
    before: gp env WIDGET_URL=$(gp url 8080) && eval $(gp env -e)
    init: cd server && npm ci
    command: cd server && npm run start
  - name: Widget
    before: gp env VUE_APP_SERVER_URL=$(gp url 3000) && eval $(gp env -e)
    init: cd widget && npm ci
    command: cd widget && npm run serve
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    visibility: public